//
// Created by Tomás Francisco on 19/06/16.
//

#ifndef CG_PROJECT_MATERIALS_HPP
#define CG_PROJECT_MATERIALS_HPP


#include "OpenGL.hpp"

#define MATERIAL_ESMERALD 1
#define MATERIAL_JADE 2
#define MATERIAL_OBSIDIAN 3
#define MATERIAL_PEARL 4
#define MATERIAL_RUBY 5
#define MATERIAL_TURQUOISE 6
#define MATERIAL_BRASS 7
#define MATERIAL_BRONZE 8
#define MATERIAL_CHROME 9
#define MATERIAL_COPPER 10
#define MATERIAL_GOLD 11
#define MATERIAL_SILVER 12
#define MATERIAL_BLACK_PLASTIC 13
#define MATERIAL_CYAN_PLASTIC 14
#define MATERIAL_GREEN_PLASTIC 15
#define MATERIAL_RED_PLASTIC 16
#define MATERIAL_WHITE_PLASTIC 17
#define MATERIAL_YELLOW_PLASTIC 18
#define MATERIAL_BLACK_RUBBER 19
#define MATERIAL_CYAN_RUBBER 20
#define MATERIAL_GREEN_RUBBER 21
#define MATERIAL_RED_RUBBER 22
#define MATERIAL_WHITE_RUBBER 23
#define MATERIAL_YELLOW_RUBBER 24

void initMaterials(int material);



#endif //CG_PROJECT_MATERIALS_HPP
